version: "3"
services:
  server-production:
    build:
      context: .
      dockerfile: server-production.dockerfile
    restart: always
    environment:
      - ADMIN_ACCOUNT_PASSWORD=${ADMIN_ACCOUNT_PASSWORD}
      - NODE_ENV=production
      - RUN_DOWNLOADER_DAEMON=${RUN_DOWNLOADER_DAEMON}
      - SESSION_SECRET=${SESSION_SECRET}
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@database-production:5432/${DB_DATABASE_NAME}?schema=public
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      database-production:
        condition: service_healthy
    volumes:
      - world_data_files:/app/temp
      - saved_maps:/app/public/images/maps
      - saved_animations:/app/public/images/animations
    command: sh -c "npx prisma migrate deploy && node server.js"
  database-production:
    image: postgres:15.4-alpine3.18
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_DATABASE_NAME} -U ${DB_USER}"]
      interval: 15s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
    driver: local
  world_data_files:
    driver: local
  saved_maps:
    driver: local
  saved_animations:
    driver: local
